apiVersion: apps/v1
kind: Deployment
metadata:
  name: slowbro
  labels:
    app.kubernetes.io/name: slowbro
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: slowbro
  template:
    metadata:
      labels:
        app.kubernetes.io/name: slowbro
    spec:
      containers:
        - name: slowbro
          image: jin/fast-api
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          command: [ 'uvicorn' ]
          args: [ 'app.main:app',  '--port=8080', '--host=0.0.0.0']
---

apiVersion: v1
kind: Service
metadata:
  name: slowbro
  labels:
    run: slowbro
spec:
  type: LoadBalancer     # 서비스 타입
  ports:
    - port: 8080       # 서비스 포트
      targetPort: 8000   # 타켓, 즉 pod의 포트
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: slowbro